// import bootstrap icons
import "bootstrap-icons/font/bootstrap-icons.css";
// import bootstrap
import "bootstrap/dist/css/bootstrap.css";
// import aos css
import "aos/dist/aos.css";

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { EB_Garamond } from "next/font/google";

import Header from "@/components/Header";

import "./variables.css";
import "./globals.css";

const ebGaramond = EB_Garamond({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "blogg news",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
    apple: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ebGaramond.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
